# Generated by Django 4.2.6 on 2023-11-05 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='Administrador', max_length=50)),
                ('descripcion', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=50)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administradorApp.cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administradorApp.rol'),
        ),
    ]
