# Generated by Django 4.2.6 on 2023-12-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradorApp', '0003_pedido_productos_alter_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comuna',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
