# Generated by Django 4.2.6 on 2023-12-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradorApp', '0004_pedido_ciudad_pedido_comuna_pedido_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='ciudad',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='comuna',
            field=models.CharField(default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
