# Generated by Django 4.2.6 on 2023-12-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradorApp', '0007_pedido_usuario_destino_alter_detallepedido_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='carrito',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
