# Generated by Django 4.2.6 on 2023-12-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradorApp', '0009_remove_pedido_carrito_usuarios_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(null=True),
        ),
    ]
