# Generated by Django 4.2.6 on 2023-12-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradorApp', '0010_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('enProceso', 'En proceso'), ('enviado', 'Enviado'), ('cancelado', 'Cancelado'), ('entregado', 'Entregado')], default='En proceso', max_length=50),
        ),
    ]
