# Generated by Django 4.2.6 on 2023-12-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradorApp', '0011_pedido_telefono_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='password',
            field=models.CharField(max_length=350),
        ),
    ]
