# Generated by Django 4.2.6 on 2023-12-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradorApp', '0013_cuenta_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('enProceso', 'En proceso'), ('Enviado', 'Enviado'), ('Cancelado', 'Cancelado'), ('Entregado', 'Entregado')], default='En proceso', max_length=50),
        ),
    ]
