# Generated by Django 4.2.6 on 2023-12-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administradorApp', '0014_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Enviado', 'Enviado'), ('Cancelado', 'Cancelado'), ('Entregado', 'Entregado')], default='En proceso', max_length=50),
        ),
    ]
